-- Remover tabelas existentes (caso já existam)
DROP TABLE ODONTO_SINISTRO CASCADE CONSTRAINTS;
DROP TABLE ODONTO_PROCEDIMENTO CASCADE CONSTRAINTS;
DROP TABLE ODONTO_CONSULTA CASCADE CONSTRAINTS;
DROP TABLE ODONTO_CLINICA CASCADE CONSTRAINTS;
DROP TABLE ODONTO_DENTISTA CASCADE CONSTRAINTS;
DROP TABLE ODONTO_PACIENTE CASCADE CONSTRAINTS;
DROP TABLE ODONTO_PLANO CASCADE CONSTRAINTS;
DROP TABLE ODONTO_ENDERECO CASCADE CONSTRAINTS;
DROP TABLE ODONTO_SCORING CASCADE CONSTRAINTS;

-- Tabela ODONTO_ENDERECO
CREATE TABLE ODONTO_ENDERECO (
    ID_ENDERECO NUMBER(10) PRIMARY KEY,
    LOGRADOURO VARCHAR2(255) NOT NULL,
    NUMERO VARCHAR2(10) NOT NULL,
    COMPLEMENTO VARCHAR2(100),
    BAIRRO VARCHAR2(100) NOT NULL,
    CIDADE VARCHAR2(100) NOT NULL,
    ESTADO VARCHAR2(2) NOT NULL,
    CEP VARCHAR2(10) NOT NULL
);

-- Tabela ODONTO_PLANO
CREATE TABLE ODONTO_PLANO (
    ID_PLANO NUMBER(10) PRIMARY KEY,
    NOME_PLANO VARCHAR2(100) NOT NULL,
    TIPO_PLANO VARCHAR2(50) NOT NULL,
    VALOR_PLANO NUMBER(10, 2) NOT NULL
);

-- Tabela ODONTO_PACIENTE (com FREQUENCIA_ESCOVACAO)
CREATE TABLE ODONTO_PACIENTE (
    ID_PACIENTE NUMBER(10) PRIMARY KEY,
    NOME_PACIENTE VARCHAR2(100) NOT NULL,
    DATA_NASCIMENTO_PACIENTE DATE NOT NULL,
    SEXO_PACIENTE VARCHAR2(1) NOT NULL,
    CPF_PACIENTE VARCHAR2(14) NOT NULL,
    EMAIL_PACIENTE VARCHAR2(100),
    TELEFONE_PACIENTE VARCHAR2(15) NOT NULL,
    HISTORICO_ODONTOLOGICO VARCHAR2(2000),
    FREQUENCIA_ESCOVACAO NUMBER(10) DEFAULT 0, -- Campo para IoT
    ID_ENDERECO NUMBER(10),
    ID_PLANO NUMBER(10),
    CONSTRAINT FK_PACIENTE_ENDERECO FOREIGN KEY (ID_ENDERECO) REFERENCES ODONTO_ENDERECO(ID_ENDERECO),
    CONSTRAINT FK_PACIENTE_PLANO FOREIGN KEY (ID_PLANO) REFERENCES ODONTO_PLANO(ID_PLANO)
);

-- Tabela ODONTO_DENTISTA
CREATE TABLE ODONTO_DENTISTA (
    ID_DENTISTA NUMBER(10) PRIMARY KEY,
    NOME VARCHAR2(100) NOT NULL,
    ESPECIALIDADE VARCHAR2(50) NOT NULL,
    CRO VARCHAR2(15) NOT NULL,
    TAXA_SINISTROS NUMBER(5, 2) DEFAULT 0,
    ID_ENDERECO NUMBER(10),
    CONSTRAINT FK_DENTISTA_ENDERECO FOREIGN KEY (ID_ENDERECO) REFERENCES ODONTO_ENDERECO(ID_ENDERECO)
);

-- Tabela ODONTO_CLINICA
CREATE TABLE ODONTO_CLINICA (
    ID_CLINICA NUMBER(10) PRIMARY KEY,
    NOME_CLINICA VARCHAR2(100) NOT NULL,
    TIPO_ATENDIMENTO VARCHAR2(50) NOT NULL,
    ID_ENDERECO NUMBER(10),
    CONSTRAINT FK_CLINICA_ENDERECO FOREIGN KEY (ID_ENDERECO) REFERENCES ODONTO_ENDERECO(ID_ENDERECO)
);

-- Tabela ODONTO_CONSULTA
CREATE TABLE ODONTO_CONSULTA (
    ID_CONSULTA NUMBER(10) PRIMARY KEY,
    DATA_CONSULTA DATE NOT NULL,
    HORA_CONSULTA VARCHAR2(5) NOT NULL,
    MOTIVO_CONSULTA VARCHAR2(255) NOT NULL,
    TIPO_CONSULTA VARCHAR2(50) NOT NULL,
    STATUS_CONSULTA VARCHAR2(20) DEFAULT 'Realizada',
    TEMPO_MEDIO_ESPERA NUMBER(10, 2),
    ID_PACIENTE NUMBER(10) NOT NULL,
    ID_DENTISTA NUMBER(10) NOT NULL,
    CONSTRAINT FK_CONSULTA_PACIENTE FOREIGN KEY (ID_PACIENTE) REFERENCES ODONTO_PACIENTE(ID_PACIENTE),
    CONSTRAINT FK_CONSULTA_DENTISTA FOREIGN KEY (ID_DENTISTA) REFERENCES ODONTO_DENTISTA(ID_DENTISTA)
);

-- Tabela ODONTO_PROCEDIMENTO
CREATE TABLE ODONTO_PROCEDIMENTO (
    ID_PROCEDIMENTO NUMBER(10) PRIMARY KEY,
    TIPO_PROCEDIMENTO VARCHAR2(100) NOT NULL,
    CUSTO_PROCEDIMENTO NUMBER(10, 2) NOT NULL,
    ID_CONSULTA NUMBER(10) NOT NULL,
    CONSTRAINT FK_PROCEDIMENTO_CONSULTA FOREIGN KEY (ID_CONSULTA) REFERENCES ODONTO_CONSULTA(ID_CONSULTA)
);

-- Tabela ODONTO_SINISTRO
CREATE TABLE ODONTO_SINISTRO (
    ID_SINISTRO NUMBER(10) PRIMARY KEY,
    DATA_SINISTRO DATE NOT NULL,
    VALOR_SINISTRO NUMBER(10, 2) NOT NULL,
    ID_CONSULTA NUMBER(10) NOT NULL,
    CAUSA_SINISTRO VARCHAR2(255),
    STATUS_SINISTRO VARCHAR2(20) DEFAULT 'Aberto',
    CONSTRAINT FK_SINISTRO_CONSULTA FOREIGN KEY (ID_CONSULTA) REFERENCES ODONTO_CONSULTA(ID_CONSULTA)
);

-- Tabela ODONTO_SCORING
CREATE TABLE ODONTO_SCORING (
    ID_SCORING NUMBER(10) PRIMARY KEY,
    ID_DENTISTA NUMBER(10) NOT NULL,
    SCORING NUMBER(5, 2) NOT NULL,
    DATA_AVALIACAO DATE NOT NULL,
    CONSTRAINT FK_SCORING_DENTISTA FOREIGN KEY (ID_DENTISTA) REFERENCES ODONTO_DENTISTA(ID_DENTISTA)
);